const FETCH_USERS = 'USER/FETCH_USERS';
const ADD_USER = 'USER/ADD_USER';
const DELETE_USER = 'USER/DELETE_USER';
const FETCH_COURSES = 'COURSES/FETCH_COURSES';
const CLEAR_VISITS = 'STATISTICS/CLEAR_VISITS';
const ADD_VISITS = 'STATISTICS/ADD_VISITS'

module.exports = {
  FETCH_COURSES, FETCH_USERS, ADD_USER, CLEAR_VISITS, ADD_VISITS, DELETE_USER
}
